name: "GitHub Action for committing changes to repository"
author: "Krzysztof Szyper <biotyk@mail.com>"
description: "GitHub Action that will create a new commit and push it back to the repository."
inputs:
  github_token:
    description: "Personal Access Token for GitHub for pushing the code."
    required: true
    default: ""
  commit_prefix:
    description: "Prefix added to commit message."
    required: false
    default: "[AUTO-COMMIT]"
  branch_name:
    description: "Name of a new branch to push the code into."
    required: false
    default: "auto-branch"
  add_timestamp:
    description: "Whether to add timestamp to a new branch name. Used when branch_name is set."
    required: false
    default: "false"
outputs:
  files_changed:
    description: "List of changed files."
runs:
  using: "docker"
  image: "docker://christophshyper/action-commit-push:latest"
branding:
  color: "white"
  icon: "wind"
